package com.nov.openview.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nov.openview.bean.CollectionDetailsBean;

import com.nov.openview.db.CollectionDetailsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionDetailsBeanDaoConfig;

    private final CollectionDetailsBeanDao collectionDetailsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionDetailsBeanDaoConfig = daoConfigMap.get(CollectionDetailsBeanDao.class).clone();
        collectionDetailsBeanDaoConfig.initIdentityScope(type);

        collectionDetailsBeanDao = new CollectionDetailsBeanDao(collectionDetailsBeanDaoConfig, this);

        registerDao(CollectionDetailsBean.class, collectionDetailsBeanDao);
    }
    
    public void clear() {
        collectionDetailsBeanDaoConfig.clearIdentityScope();
    }

    public CollectionDetailsBeanDao getCollectionDetailsBeanDao() {
        return collectionDetailsBeanDao;
    }

}
